# ==============================================================================
# FusionOS Global Graphics & Wayland Acceleration Environment
# ==============================================================================

# Shader Cache de 10GB para eliminação de engasgos (Zero Stutter)
MESA_SHADER_CACHE_MAX_SIZE=10G

# Compilador ACO e Smart Access Memory (SAM) para placas Radeon
RADV_PERFTEST=aco,sam

# Variáveis para suporte a VRR / G-Sync em NVIDIA Wayland
__GL_VRR_ALLOWED=1
__GL_GSYNC_ALLOWED=1

# Aceleração nativa Wayland em navegadores e apps Electron (Discord, Spotify, VS Code)
MOZ_ENABLE_WAYLAND=1
ELECTRON_OZONE_PLATFORM_HINT=auto
QT_QPA_PLATFORM=wayland;xcb
GDK_BACKEND=wayland,x11
