# ==============================================================================
# FusionOS - Studio-Grade Low-Latency Audio Profile (PipeWire)
# Proposito: Entrega latencia de audio de padrao macOS CoreAudio (~2 a 5ms)
#            eliminando atrasos em games de tiro (FPS), microfone e instrumentos.
# ==============================================================================

context.properties = {
    default.clock.rate          = 48000
    default.clock.allowed-rates = [ 44100 48000 88200 96000 192000 ]
    default.clock.quantum       = 256
    default.clock.min-quantum   = 64
    default.clock.max-quantum   = 1024
}

