# ==============================================================================
# FusionOS Unlocked Bluetooth Hi-Res Audio Configuration (WirePlumber)
# Proposito: Remove as travas do Bluetooth e ativa LDAC 990kbps, aptX-HD e SBC-XQ
# ==============================================================================

monitor.bluez.properties = {
    # Prioridade de codecs Bluetooth (do mais avancado ao basico)
    bluez5.codecs = [ ldac aptx_hd aptx aac sbc_xq sbc ]

    # Ativa LDAC da Sony em taxa maxima de 990 kbps (24-bit / 96kHz)
    bluez5.enable-sbc-xq = true
    bluez5.enable-msbc   = true
    bluez5.enable-hw-volume = true

    # Previne que a troca para microfone destrua a qualidade da musica
    bluez5.roles = [ a2dp_sink a2dp_source bap_sink bap_source hsp_hs hsp_ag hfp_hf hfp_ag ]
}

monitor.bluez.rules = [
    {
        matches = [
            {
                # Aplica a todos os dispositivos de saida Bluetooth
                device.name = "~bluez_card.*"
            }
        ]
        actions = {
            update-props = {
                bluez5.auto-connect = [ a2dp_sink ]
                bluez5.hw-volume = [ a2dp_sink ]
            }
        }
    }
]
