# ==============================================================================
# FusionOS - ZRAM RAM Compression Engine
# Proposito: Compacta dados diretamente na memoria RAM usando o algoritmo ZSTD.
# Um PC com 8GB se comporta como se tivesse ~14GB a 16GB, sem lentidao de swap em disco.
# ==============================================================================

[zram0]
zram-size = ram
compression-algorithm = zstd
swap-priority = 100
fs-type = swap

